name: 更新 README

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 0 点运行
  workflow_dispatch:      # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装依赖
        run: pip install requests
        
      - name: 运行脚本更新 README
        run: |
          python update_readme.py

      - name: 提交更改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "update README" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
  generate-snake:
    runs-on: ubuntu-latest
    needs: update-readme
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 生成贪吃蛇贡献动画
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kalaser   # ← 改成你的 GitHub 用户名 
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: 拉取每日一图
        run: |
              mkdir -p dist
              curl -L "https://60s.viki.moe/v2/bing?encoding=image" -o dist/daily.jpg

      - name: 推送到 output 分支
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

